// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP949ZtGah5WkfAScXiOzFzWGganLHAR4',
    appId: '1:940187507737:web:09327bf9d0b7805058de88',
    messagingSenderId: '940187507737',
    projectId: 'solidcheck-5e0eb',
    authDomain: 'solidcheck-5e0eb.firebaseapp.com',
    storageBucket: 'solidcheck-5e0eb.appspot.com',
    measurementId: 'G-C9KJ02JRTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHulLbWJgy3k6eDHEYl-sBnFPyQwYmDs',
    appId: '1:940187507737:android:0f36a8c8538d68b058de88',
    messagingSenderId: '940187507737',
    projectId: 'solidcheck-5e0eb',
    storageBucket: 'solidcheck-5e0eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACP4CQ4yseNTrWvOgbwTtE6GbWgAuz7Uc',
    appId: '1:940187507737:ios:b2b4e565b6bb294f58de88',
    messagingSenderId: '940187507737',
    projectId: 'solidcheck-5e0eb',
    storageBucket: 'solidcheck-5e0eb.appspot.com',
    iosBundleId: 'com.example.solidcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACP4CQ4yseNTrWvOgbwTtE6GbWgAuz7Uc',
    appId: '1:940187507737:ios:b2b4e565b6bb294f58de88',
    messagingSenderId: '940187507737',
    projectId: 'solidcheck-5e0eb',
    storageBucket: 'solidcheck-5e0eb.appspot.com',
    iosBundleId: 'com.example.solidcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP949ZtGah5WkfAScXiOzFzWGganLHAR4',
    appId: '1:940187507737:web:15e7ea3f3631f36558de88',
    messagingSenderId: '940187507737',
    projectId: 'solidcheck-5e0eb',
    authDomain: 'solidcheck-5e0eb.firebaseapp.com',
    storageBucket: 'solidcheck-5e0eb.appspot.com',
    measurementId: 'G-W4JJ3XRBC1',
  );

}